// Generated by npm run build:music:display-covers. No runtime image encoding.
export const musicDisplayCoverManifest = Object.freeze({
  "a0c56db23c24efc3eaeb0fa0bda8ba62ed96a8fc28efa478d30f1f2098ef9c32": {
    "path": "/api/music/__cover-files/2c3799a1c3a1d7c58ede726f0b52748106c88bb3e37cf87a57d8c0309fb5db65.jpg",
    "sha256": "2c3799a1c3a1d7c58ede726f0b52748106c88bb3e37cf87a57d8c0309fb5db65",
    "bytes": 90565,
    "sourceBytes": 2020974,
    "contentType": "image/jpeg"
  },
  "cd7b7ceb8181cc1b001cf190de8d086c92db829d8025bd1d2d876c2cb643c90e": {
    "path": "/api/music/__cover-files/0095ddbba163ccde116e17b2bd7eeb2918630f33db064cfc9642aa03b519f748.jpg",
    "sha256": "0095ddbba163ccde116e17b2bd7eeb2918630f33db064cfc9642aa03b519f748",
    "bytes": 89682,
    "sourceBytes": 1897879,
    "contentType": "image/jpeg"
  },
  "ed654775fb5f9c8f383ba3eeda74980ee968f57c5e52a0de119ffdf1d6347ccf": {
    "path": "/api/music/__cover-files/3e9309b2c43d04c6142d3047b5cab74b27e6baeff6bfa285a8b8a00c9f99870e.jpg",
    "sha256": "3e9309b2c43d04c6142d3047b5cab74b27e6baeff6bfa285a8b8a00c9f99870e",
    "bytes": 87173,
    "sourceBytes": 1958295,
    "contentType": "image/jpeg"
  },
  "3fa7e2ff7a2973e2d206b4984b74c077bf13439b9f9d39d5bf3a03697b036303": {
    "path": "/api/music/__cover-files/aea4449c7880d163e2b2852f1aafd045aa8444aef8b232d18751cb8dd3280c89.jpg",
    "sha256": "aea4449c7880d163e2b2852f1aafd045aa8444aef8b232d18751cb8dd3280c89",
    "bytes": 89530,
    "sourceBytes": 2222157,
    "contentType": "image/jpeg"
  },
  "54b38557349315b23898f7d24278a7a4762e1429746c872aba3cb5cf47e0e06a": {
    "path": "/api/music/__cover-files/9eb950178930259dd68bd7239107ff92415e39641a4177c132c7de4edceb84a8.jpg",
    "sha256": "9eb950178930259dd68bd7239107ff92415e39641a4177c132c7de4edceb84a8",
    "bytes": 146095,
    "sourceBytes": 2546928,
    "contentType": "image/jpeg"
  },
  "cfc3ddecdce790babebc36750482fd5ae5df9025bb669137acd0f534a64291cc": {
    "path": "/api/music/__cover-files/8a13ef5ee1e67373108127b8eeeef953f082aa1db33e5df3410e83f34c88853a.jpg",
    "sha256": "8a13ef5ee1e67373108127b8eeeef953f082aa1db33e5df3410e83f34c88853a",
    "bytes": 71917,
    "sourceBytes": 1970711,
    "contentType": "image/jpeg"
  },
  "ed75682a4c9565bbdaa92e4796db94599efea87ef97f9a5b6d5baf8a6c31d531": {
    "path": "/api/music/__cover-files/d7fadb52cdd90fe7d95ab5936e8ceafdaffcefa5b9cbffb1638768b1587ba5da.jpg",
    "sha256": "d7fadb52cdd90fe7d95ab5936e8ceafdaffcefa5b9cbffb1638768b1587ba5da",
    "bytes": 125863,
    "sourceBytes": 2413049,
    "contentType": "image/jpeg"
  },
  "79ad0b79278e6c764e2e2c0d61329295dccbb7840d5c8a352f44f41fa417f1b5": {
    "path": "/api/music/__cover-files/be9333d5aa555e40c55004ffe5394f36aae6bfdf9d714efc01589df8bd72f9dc.jpg",
    "sha256": "be9333d5aa555e40c55004ffe5394f36aae6bfdf9d714efc01589df8bd72f9dc",
    "bytes": 93619,
    "sourceBytes": 1996676,
    "contentType": "image/jpeg"
  }
});
