export const aboutCopy = Object.freeze({
  'zh-Hant': { title: '關於小站', headline: '把創作，放進日常。', intro: 'Station Cat 是一個關於音樂、遊戲與生活靈感的個人創作小站。',
    body: '用音樂記錄情緒，用遊戲描繪想像，也分享那些讓日常變得柔軟的時刻。願每一次停留，都能遇見一點溫暖。',
    music: '讓音樂走得更遠', musicText: '這裡分享作品故事、短影片與正式平台收聽入口。歌曲主要在各大音樂平台發行，站內試聽依每首作品的安排開放。',
    games: '一起走進小冒險', gamesText: '在遊戲裡留住生活的片刻，與貓咪一起探索新的故事。',
    member: '你的小站', memberText: '登入現有帳號，查看會員、歷史權益與遊戲存檔。', back: '回到首頁' },
  'zh-Hans': { title: '关于小站', headline: '把创作，放进日常。', intro: 'Station Cat 是一个关于音乐、游戏与生活灵感的个人创作小站。',
    body: '用音乐记录情绪，用游戏描绘想象，也分享那些让日常变得柔软的时刻。愿每一次停留，都能遇见一点温暖。',
    music: '让音乐走得更远', musicText: '这里分享作品故事、短视频与正式平台收听入口。歌曲主要在各大音乐平台发行，站内试听依每首作品的安排开放。',
    games: '一起走进小冒险', gamesText: '在游戏里留住生活的片刻，与猫咪一起探索新的故事。',
    member: '你的小站', memberText: '登录现有账号，查看会员、历史权益与游戏存档。', back: '回到首页' },
  en: { title: 'About the station', headline: 'A little room for everyday creativity.', intro: 'Station Cat is a personal creative home for music, games, and everyday inspiration.',
    body: 'Music holds a feeling. Games give imagination a place to wander. Here, small moments of warmth become stories to share.',
    music: 'Let a song travel', musicText: 'Explore song stories, short videos, and official listening links. Most songs are released on music platforms; on-site previews are arranged for each work.',
    games: 'Step into a little adventure', gamesText: 'Discover everyday moments and new stories with cats, one small adventure at a time.',
    member: 'Your station', memberText: 'Use your existing account to view membership, past entitlements, and game saves.', back: 'Back home' },
  ja: { title: '小さな駅について', headline: '創作を、日常のそばに。', intro: 'Station Cat は、音楽とゲーム、日々のひらめきを集めた個人の創作サイトです。',
    body: '音楽で気持ちを記録し、ゲームで想像の世界を描く。日常を少しやさしくする瞬間を、ここでお届けします。',
    music: '歌を、もっと遠くへ', musicText: '楽曲の物語、短い映像、正式な配信リンクを紹介します。楽曲は主に音楽配信サービスで公開し、サイト内の試聴は作品ごとに設定します。',
    games: '小さな冒険へ', gamesText: '猫と一緒に、暮らしのひとこまや新しい物語を見つけていきましょう。',
    member: 'あなたの小さな駅', memberText: '既存のアカウントで、会員情報、過去の権利、ゲームのセーブを確認できます。', back: 'ホームへ' },
});
