import { gameCopy } from './gameCopy.js';
import { stationHref } from './routes.js';
import { escapeMusicHtml as e } from './musicRender.js';
const icon = name => `<svg width="22" height="22" aria-hidden="true"><use href="#sc-game-${name}"></use></svg>`;
const devices = (game, copy) => game.supportedDevices.map(device => `<span>${['desktop', 'mobile'].includes(device) ? icon(device) : ''}${e(copy[device] || device)}</span>`).join('');
const image = (game, copy, className = '') => game.screenshots[0] ? `<img class="${className}" src="${e(game.screenshots[0].url)}" alt="${e(game.title + ' · ' + copy.alt)}" width="1280" height="900" loading="lazy">` : '';
export function renderGamePage(model) {
  const copy = gameCopy[model.locale], back = stationHref(model.locale, 'games');
  const top = `<header class="sc-game-heading"><p class="sc-game-kicker">${copy.kicker}</p><h1 class="sc-heading">${e(model.game?.title || copy.title)}</h1><p>${e(model.game?.summary || copy.intro)}</p></header>`;
  if (model.error) return `<section class="sc-game-page sc-container">${top}<div class="sc-game-empty"><h2>${copy.failed}</h2><a class="sc-button" href="${back}">${copy.retry}</a></div></section>`;
  if (model.mode === 'catalog') return `<section class="sc-game-page sc-container">${top}<h2 class="sc-game-section-title">${copy.featured}</h2><div class="sc-game-grid">${model.items.map(game => `<article class="sc-game-card">${image(game, copy, 'sc-game-cover')}<div class="sc-game-card-copy"><div class="sc-game-devices">${devices(game, copy)}</div><h2>${e(game.title)}</h2><p>${e(game.summary)}</p><a class="sc-button" href="${e(game.href)}">${copy.detail}${icon('arrow')}</a></div></article>`).join('') || `<p class="sc-game-empty">${copy.empty}</p>`}</div>${model.nextCursor ? `<a class="sc-button sc-button-secondary sc-game-more" href="${back}?cursor=${encodeURIComponent(model.nextCursor)}">${copy.next}</a>` : ''}</section>`;
  const game = model.game;
  return `<section class="sc-game-page sc-container"><a class="sc-game-back" href="${back}">${icon('arrow')}${copy.back}</a>${top}<div class="sc-game-detail"><div class="sc-game-gallery"><h2>${copy.screen}</h2>${game.screenshots.map((shot, index) => `<a href="${e(shot.url)}" target="_blank" rel="noopener" aria-label="${e(copy.screen + ' ' + (index + 1))}"><img src="${e(shot.url)}" alt="${e(game.title + ' · ' + copy.alt + ' ' + (index + 1))}" width="1280" height="900" loading="${index ? 'lazy' : 'eager'}"></a>`).join('') || `<p class="sc-game-empty">${copy.screenPending}</p>`}</div><aside class="sc-game-save"><span class="sc-game-save-icon">${icon('shield')}</span><h2>${copy.save}</h2><p>${copy.saveNote}</p>${game.launchPath === '/games/cat-life/' ? `<div class="sc-game-check" data-sc-game-entry><p data-sc-game-status role="status">${copy.checking}</p><a class="sc-button" data-sc-game-launch hidden></a><button class="sc-button sc-button-secondary" type="button" data-sc-game-retry>${copy.retry}</button><noscript><p>${copy.saveNote}</p><a href="/games/cat-life/?sc_entry=1">${copy.enter}</a></noscript></div>` : `<p>${copy.unavailableLaunch}</p>`}<a class="sc-game-member" href="${stationHref(model.locale, 'member')}">${copy.member}</a><details><summary>${copy.moreSave}</summary><p>${copy.otherSave}</p></details></aside></div><section class="sc-game-device-note"><h2>${copy.devices}</h2><div class="sc-game-devices">${devices(game, copy)}</div><p>${copy.deviceNote}</p>${game.launchPath === '/games/cat-life/' ? `<p>${copy.language}</p>` : ''}</section></section>`;
}
