// User-approved brand copy. Work/sample copy is used only by isolated consumers.
export const homeCopy = {
  'zh-Hant': {
    pageTitle: '溫柔小站 · T04 設計預覽', headline: ['把音樂、遊戲與溫柔日常，', '放進同一座小站。'],
    intro: ['Station Cat 是一個關於音樂、遊戲與生活靈感的創作小站。', '在這裡，我用音樂記錄情緒，用遊戲描繪想像，', '也希望和你分享那些讓日常變得柔軟的時刻。'],
    goMusic: '前往音樂小站', goGames: '探索遊戲世界', music: '音樂小站', musicTagline: '選一首，讓日常慢下來。', moreMusic: '探索更多音樂',
    song: '晚一點告白', musicSample: '示例作品', songText: ['寫給還沒說出口的心意，', '也寫給每一個溫柔的夜晚。'], noPreview: '站內試聽尚未配置',
    pending: '待配置', pendingPlatform: '平台連結稍後確定', netease: '網易雲音樂', qishui: '汽水音樂', video: '音樂短影片',
    games: '遊戲世界', gamesTagline: '一邊生活，一邊冒險。', moreGames: '探索更多遊戲', game: '打工養貓日記', gameSample: '遊戲示例',
    gameText: ['在一座溫柔的小鎮，', '和貓咪一起工作、生活、發現更多可能。', '這是一款關於日常與夢想的療癒遊戲。'], viewGame: '查看遊戲', wishlist: '加入願望清單', wishlisted: '已加入清單', wishlistNotice: '已加入本次預覽清單，未同步至帳號。',
    promotion: '讓好音樂被更多人聽見', promotionText: '從創作、發行到分享，這裡是通往你我的音樂樞紐。',
    complete: '完整歌曲', completeText: '原創作品與創作分享', platforms: '平台收聽', platformText: '串連各大音樂平台', shortVideo: '短影片推廣', videoText: '用影像留住音樂', member: '會員內容', memberText: '支持創作，解鎖更多',
    latest: '最新動態', latestText: '最近的音樂、遊戲與生活片段', viewAll: '查看全部', songNews: ['寫給深夜的一首歌，', '願意陪你度過某個安靜的夜晚。'], gameNews: ['小鎮迎來新的季節。', '一起繼續生活，一起發現更多故事吧！'], daily: '小站日常', stationTitle: '深夜的小站', stationNews: ['無論多晚，', '這裡都會為喜歡音樂與遊戲的你，', '留一盞燈。'], view: '查看',
    heroAlt: '暮色中的小站：戴耳機的黑白貓、亮著燈的城市、咖啡杯與音樂遊戲書本。', musicAlt: '設計示例封面：黑貓望著黃昏的河岸城市，標題為晚一點告白。', gameAlt: '設計示例遊戲插畫：背著棕色背包的黑貓望向晴天下的海邊小鎮。',
  },
  'zh-Hans': {
    pageTitle: '温柔小站 · T04 设计预览', headline: ['把音乐、游戏与温柔日常，', '放进同一座小站。'],
    intro: ['Station Cat 是一个关于音乐、游戏与生活灵感的创作小站。', '在这里，我用音乐记录情绪，用游戏描绘想象，', '也希望和你分享那些让日常变得柔软的时刻。'],
    goMusic: '前往音乐小站', goGames: '探索游戏世界', music: '音乐小站', musicTagline: '选一首，让日常慢下来。', moreMusic: '探索更多音乐',
    song: '晚一点告白', musicSample: '示例作品', songText: ['写给还没说出口的心意，', '也写给每一个温柔的夜晚。'], noPreview: '站内试听尚未配置',
    pending: '待配置', pendingPlatform: '平台链接稍后确定', netease: '网易云音乐', qishui: '汽水音乐', video: '音乐短视频',
    games: '游戏世界', gamesTagline: '一边生活，一边冒险。', moreGames: '探索更多游戏', game: '打工养猫日记', gameSample: '游戏示例',
    gameText: ['在一座温柔的小镇，', '和猫咪一起工作、生活、发现更多可能。', '这是一款关于日常与梦想的治愈游戏。'], viewGame: '查看游戏', wishlist: '加入愿望清单', wishlisted: '已加入清单', wishlistNotice: '已加入本次预览清单，未同步至账号。',
    promotion: '让好音乐被更多人听见', promotionText: '从创作、发行到分享，这里是通往你我的音乐枢纽。',
    complete: '完整歌曲', completeText: '原创作品与创作分享', platforms: '平台收听', platformText: '串连各大音乐平台', shortVideo: '短视频推广', videoText: '用影像留住音乐', member: '会员内容', memberText: '支持创作，解锁更多',
    latest: '最新动态', latestText: '最近的音乐、游戏与生活片段', viewAll: '查看全部', songNews: ['写给深夜的一首歌，', '愿意陪你度过某个安静的夜晚。'], gameNews: ['小镇迎来新的季节。', '一起继续生活，一起发现更多故事吧！'], daily: '小站日常', stationTitle: '深夜的小站', stationNews: ['无论多晚，', '这里都会为喜欢音乐与游戏的你，', '留一盏灯。'], view: '查看',
    heroAlt: '暮色中的小站：戴耳机的黑白猫、亮着灯的城市、咖啡杯与音乐游戏书本。', musicAlt: '设计示例封面：黑猫望着黄昏的河岸城市，标题为晚一点告白。', gameAlt: '设计示例游戏插画：背着棕色背包的黑猫望向晴天下的海边小镇。',
  },
  en: {
    pageTitle: 'A gentle little station · T04 preview', headline: ['Music, games, and everyday warmth,', 'all in one little station.'],
    intro: ['Station Cat is a creative home for music, games, and everyday ideas.', 'I make music to hold a feeling, and games to explore an imagination.', 'Come share the little moments that make life softer.'],
    goMusic: 'Visit the music station', goGames: 'Explore the games', music: 'Music station', musicTagline: 'A song to slow the day down.', moreMusic: 'More music',
    song: '晚一點告白', musicSample: 'Design sample', songText: ['For the words we haven’t said yet,', 'and every gentle evening.'], noPreview: 'On-site preview is not configured',
    pending: 'Coming soon', pendingPlatform: 'Platform links to be confirmed', netease: 'NetEase Music', qishui: 'Qishui Music', video: 'Music videos',
    games: 'Game world', gamesTagline: 'A little life, a little adventure.', moreGames: 'More games', game: 'Cat Life Diary', gameSample: 'Game sample',
    gameText: ['In a warm little town,', 'work, live, and discover with your cat.', 'A gentle game about everyday dreams.'], viewGame: 'View the game', wishlist: 'Add to wishlist', wishlisted: 'Added to list', wishlistNotice: 'Added for this preview only; not synced to an account.',
    promotion: 'Let good music find more ears', promotionText: 'From creating to sharing: a small station connecting us.',
    complete: 'Full songs', completeText: 'Original music & stories', platforms: 'Listen elsewhere', platformText: 'Across music platforms', shortVideo: 'Short videos', videoText: 'Music through a lens', member: 'Member space', memberText: 'Support more creations',
    latest: 'Latest stories', latestText: 'Music, games, and moments of everyday life', viewAll: 'View all', songNews: ['A song for a quiet night,', 'a little company after dark.'], gameNews: ['A new season in the little town.', 'More life, more stories to discover.'], daily: 'Station life', stationTitle: 'The station after dark', stationNews: ['However late it gets,', 'a light stays on for everyone', 'who loves music and games.'], view: 'Explore',
    heroAlt: 'A twilight station: a tuxedo cat wearing headphones, city lights, coffee, and music and game books.', musicAlt: 'Design sample cover: a black cat overlooking a riverside city at dusk, titled 晚一點告白.', gameAlt: 'Design sample game art: a black cat with a brown backpack looking toward a sunny seaside town.',
  },
  ja: {
    pageTitle: 'やさしい小さな駅 · T04 プレビュー', headline: ['音楽とゲーム、やさしい日常を、', 'ひとつの小さな駅に。'],
    intro: ['Station Cat は音楽、ゲーム、日々のひらめきが集まる創作の場所。', '音楽で気持ちを残し、ゲームで想像を描きます。', '暮らしが少しやわらぐ瞬間を、あなたと分かち合いたい。'],
    goMusic: '音楽の小さな駅へ', goGames: 'ゲームの世界を探す', music: '音楽の小さな駅', musicTagline: '一曲で、日常をゆっくりと。', moreMusic: '音楽をもっと見る',
    song: '晚一點告白', musicSample: 'デザイン例', songText: ['まだ言葉にできない気持ちと、', 'やさしい夜に寄り添う一曲。'], noPreview: '試聴はまだ設定されていません',
    pending: '後日ご案内', pendingPlatform: '配信リンクは後日確定', netease: 'NetEase Music', qishui: 'Qishui Music', video: '音楽動画',
    games: 'ゲームの世界', gamesTagline: '暮らしながら、冒険しよう。', moreGames: 'ゲームをもっと見る', game: '猫との暮らし日記', gameSample: 'ゲームの例',
    gameText: ['やさしい小さな町で、', '猫と働き、暮らし、発見しよう。', '日常と夢を描く、心やすらぐゲーム。'], viewGame: 'ゲームを見る', wishlist: 'ほしい物リストへ', wishlisted: '追加しました', wishlistNotice: 'このプレビュー内のみの追加です。アカウントには同期されません。',
    promotion: 'いい音楽を、もっと多くの人へ', promotionText: '創作から発信まで、私たちをつなぐ音楽の駅。',
    complete: '楽曲', completeText: 'オリジナル作品と物語', platforms: '配信で聴く', platformText: '音楽配信サービスへ', shortVideo: 'ショート動画', videoText: '映像で音楽を届ける', member: '会員コンテンツ', memberText: '創作を応援する',
    latest: '新しいお便り', latestText: '音楽、ゲーム、日常のひとこま', viewAll: 'すべて見る', songNews: ['静かな夜に寄り添う一曲。', '穏やかな時間のおともに。'], gameNews: ['小さな町に新しい季節。', '暮らしと物語を一緒に見つけよう。'], daily: '駅の日常', stationTitle: '夜更けの小さな駅', stationNews: ['どんなに遅い夜も、', '音楽とゲームを愛するあなたに、', 'ひとつの灯りを残します。'], view: '詳しく見る',
    heroAlt: '夕暮れの小さな駅：ヘッドホンをつけた白黒猫、街の灯り、コーヒーと音楽・ゲームの本。', musicAlt: 'デザイン例のジャケット：夕暮れの川沿いの街を眺める黒猫。題名は晚一點告白。', gameAlt: 'デザイン例のゲームイラスト：茶色のリュックを背負った黒猫が晴れた海辺の町を眺めている。',
  },
};
