export const memberCopy = Object.freeze({
  'zh-Hant': {
    title: '會員小站', intro: '收藏喜歡的音樂，照顧每一段遊戲進度。',
    authHeading: '歡迎回到你的小站。', authDesc: '沿用你的 Station Cat 帳號，查看會員、積分與已購權益。',
    services: '我的收藏與服務', servicesIntro: '音樂在這台裝置，帳號權益與雲端進度各有歸屬。',
    music: '本機音樂收藏', musicIntro: '保存在此裝置與瀏覽器，登入不會自動上傳。',
    favorites: '收藏', recent: '最近播放', count: '{count} 首', emptyMusic: '還沒有本機收藏。到音樂小站找到喜歡的作品吧。',
    emptyRecent: '這台裝置還沒有最近播放紀錄。', openMusic: '前往音樂小站', more: '顯示更多',
    savedTrack: '已存作品 {number}', trackMissing: '作品暫不可用（{id}）', trackUnavailable: '作品資訊暫不可讀（{id}）',
    musicCorrupt: '本機音樂資料格式不相容或損壞，原資料已保留。請回到音樂頁處理。',
    musicStorage: '無法讀取此瀏覽器的本機音樂資料，不能確認收藏是否存在。',
    musicLegacy: '正在顯示舊版本機收藏；這裡不會改寫資料。',
    native: 'App 音樂資料庫', nativeIntro: 'App 收藏請在 App 內查看；網頁本機收藏不會自動同步到 App。',
    game: '遊戲存檔與裝扮', gameIntro: '本機進度與雲端存檔分開顯示，是否一致請在遊戲內確認。',
    gameOpen: '進入遊戲查看存檔', local: '本機', cloud: '雲端', checking: '正在核對…',
    identityError: '無法確認目前帳號，請重新核對。', guest: '未登入，正在查看本機遊客存檔。',
    missing: '未找到目前槽位的存檔', valid: '有可讀的本機存檔', corrupt: '存檔損壞，原文保留', unsupported: '存檔版本不相容，原文保留', unavailable: '本機儲存無法讀取',
    cloudGuest: '登入後可查看帳號雲存檔', cloudMissing: '此帳號沒有雲存檔', cloudSaved: '已有雲存檔 · 版本 {revision} · {date}', cloudError: '暫時無法確認雲存檔',
    costumes: '帳號已購裝扮：{count} 項', costumesGuest: '登入後可查看已購裝扮', costumesError: '暫時無法確認已購裝扮',
    retry: '重新核對', orders: '歷史訂單', ordersIntro: '用原訂單編號查詢付款與交付狀態。綁定帳號的訂單需登入原帳號。',
    orderLabel: '訂單編號', orderSubmit: '查詢訂單', orderRequired: '請輸入不超過 80 個字元的原訂單編號。',
    orderFound: '{status} · {amount} {currency}', fulfilled: '已完成交付', pending: '付款或交付待確認', review: '交付待人工核對', refunded: '已退款或撤銷入帳', failed: '付款未完成', expired: '訂單已過期',
    orderUnknown: '訂單狀態暫不可確認', orderNotFound: '找不到這筆訂單', orderAuth: '請登入訂單所屬帳號', orderOther: '這筆訂單屬於其他帳號', orderError: '訂單查詢暫時不可用，請稍後重試',
    support: '帳號與售後', supportIntro: '歷史購買、積分與售後沿用原規則。如需協助，請保留原訂單資料。',
    contact: '聯絡支援', points: '查看積分與退款規則', privacy: '隱私政策', terms: '服務條款',
    refreshSession: '帳號已變更，請重新核對。',
  },
  'zh-Hans': {
    title: '会员小站', intro: '收藏喜欢的音乐，照顾每一段游戏进度。',
    authHeading: '欢迎回到你的小站。', authDesc: '沿用你的 Station Cat 账号，查看会员、积分与已购权益。',
    services: '我的收藏与服务', servicesIntro: '音乐在这台设备，账号权益与云端进度各有归属。',
    music: '本机音乐收藏', musicIntro: '保存在此设备与浏览器，登录不会自动上传。',
    favorites: '收藏', recent: '最近播放', count: '{count} 首', emptyMusic: '还没有本机收藏。到音乐小站找到喜欢的作品吧。',
    emptyRecent: '这台设备还没有最近播放记录。', openMusic: '前往音乐小站', more: '显示更多',
    savedTrack: '已存作品 {number}', trackMissing: '作品暂不可用（{id}）', trackUnavailable: '作品信息暂不可读（{id}）',
    musicCorrupt: '本机音乐资料格式不兼容或损坏，原资料已保留。请回到音乐页处理。',
    musicStorage: '无法读取此浏览器的本机音乐资料，不能确认收藏是否存在。',
    musicLegacy: '正在显示旧版本机收藏；这里不会改写资料。',
    native: 'App 音乐资料库', nativeIntro: 'App 收藏请在 App 内查看；网页本机收藏不会自动同步到 App。',
    game: '游戏存档与装扮', gameIntro: '本机进度与云端存档分开显示，是否一致请在游戏内确认。',
    gameOpen: '进入游戏查看存档', local: '本机', cloud: '云端', checking: '正在核对…',
    identityError: '无法确认当前账号，请重新核对。', guest: '未登录，正在查看本机游客存档。',
    missing: '未找到当前槽位的存档', valid: '有可读的本机存档', corrupt: '存档损坏，原文保留', unsupported: '存档版本不兼容，原文保留', unavailable: '本机存储无法读取',
    cloudGuest: '登录后可查看账号云存档', cloudMissing: '此账号没有云存档', cloudSaved: '已有云存档 · 版本 {revision} · {date}', cloudError: '暂时无法确认云存档',
    costumes: '账号已购装扮：{count} 项', costumesGuest: '登录后可查看已购装扮', costumesError: '暂时无法确认已购装扮',
    retry: '重新核对', orders: '历史订单', ordersIntro: '用原订单编号查询付款与交付状态。绑定账号的订单需登录原账号。',
    orderLabel: '订单编号', orderSubmit: '查询订单', orderRequired: '请输入不超过 80 个字符的原订单编号。',
    orderFound: '{status} · {amount} {currency}', fulfilled: '已完成交付', pending: '付款或交付待确认', review: '交付待人工核对', refunded: '已退款或撤销入账', failed: '付款未完成', expired: '订单已过期',
    orderUnknown: '订单状态暂不可确认', orderNotFound: '找不到这笔订单', orderAuth: '请登录订单所属账号', orderOther: '这笔订单属于其他账号', orderError: '订单查询暂时不可用，请稍后重试',
    support: '账号与售后', supportIntro: '历史购买、积分与售后沿用原规则。如需帮助，请保留原订单资料。',
    contact: '联系支持', points: '查看积分与退款规则', privacy: '隐私政策', terms: '服务条款',
    refreshSession: '账号已变更，请重新核对。',
  },
  en: {
    title: 'Your member station', intro: 'Keep your favourite music and every little game memory close.',
    authHeading: 'Welcome back to your station.', authDesc: 'Use your existing Station Cat account for membership, points and purchased access.',
    services: 'Your collections and services', servicesIntro: 'Music stays on this device. Account access and cloud saves belong to your account.',
    music: 'Music on this device', musicIntro: 'Saved in this browser on this device. Signing in does not upload it.',
    favorites: 'Favourites', recent: 'Recently played', count: '{count} tracks', emptyMusic: 'No favourites on this device yet. Find something you love at the music station.',
    emptyRecent: 'No recently played tracks on this device yet.', openMusic: 'Visit the music station', more: 'Show more',
    savedTrack: 'Saved track {number}', trackMissing: 'Track unavailable ({id})', trackUnavailable: 'Track information unavailable ({id})',
    musicCorrupt: 'The local music data is damaged or incompatible. The original is preserved; visit Music to manage it.',
    musicStorage: 'Local music storage cannot be read. We cannot confirm whether favourites exist.',
    musicLegacy: 'Showing older local favourites. This page does not rewrite them.',
    native: 'Music in the app', nativeIntro: 'View app favourites in the app. Browser favourites do not sync automatically to the app.',
    game: 'Game saves and purchased items', gameIntro: 'Device progress and cloud saves are separate. Check their sync status inside the game.',
    gameOpen: 'Open the game to check saves', local: 'Device', cloud: 'Cloud', checking: 'Checking…',
    identityError: 'The current account could not be confirmed. Check again.', guest: 'Signed out. Showing the guest save on this device.',
    missing: 'No save in the current slot', valid: 'A readable device save exists', corrupt: 'Damaged save; original preserved', unsupported: 'Incompatible save version; original preserved', unavailable: 'Device storage cannot be read',
    cloudGuest: 'Sign in to view your account cloud save', cloudMissing: 'This account has no cloud save', cloudSaved: 'Cloud save exists · revision {revision} · {date}', cloudError: 'Cloud save cannot be confirmed right now',
    costumes: 'Purchased account items: {count}', costumesGuest: 'Sign in to view purchased game items', costumesError: 'Purchased items cannot be confirmed right now',
    retry: 'Check again', orders: 'Historical orders', ordersIntro: 'Use the original order reference to check payment and delivery. Account orders require their original account.',
    orderLabel: 'Order reference', orderSubmit: 'Check order', orderRequired: 'Enter the original order reference, up to 80 characters.',
    orderFound: '{status} · {amount} {currency}', fulfilled: 'Delivery complete', pending: 'Payment or delivery awaiting confirmation', review: 'Delivery needs review', refunded: 'Refunded or credit reversed', failed: 'Payment not completed', expired: 'Order expired',
    orderUnknown: 'Order status cannot be confirmed', orderNotFound: 'Order not found', orderAuth: 'Sign in to the account that owns this order', orderOther: 'This order belongs to another account', orderError: 'Order lookup is unavailable. Try again later.',
    support: 'Account and support', supportIntro: 'Historical purchases, points and support keep their existing rules. Keep the original order reference when requesting help.',
    contact: 'Contact support', points: 'Points and refund rules', privacy: 'Privacy policy', terms: 'Terms of service',
    refreshSession: 'Your account changed. Check again.',
  },
  ja: {
    title: 'あなたの会員ステーション', intro: 'お気に入りの音楽と、ゲームの思い出を大切に。',
    authHeading: 'おかえりなさい、あなたの小さな駅へ。', authDesc: 'これまでの Station Cat アカウントで、会員権、ポイント、購入済みの利用権を確認できます。',
    services: 'コレクションとサービス', servicesIntro: '音楽はこの端末に。利用権とクラウドセーブはアカウントごとに管理します。',
    music: 'この端末の音楽', musicIntro: 'この端末のブラウザーに保存されます。ログインしても自動でアップロードされません。',
    favorites: 'お気に入り', recent: '最近の再生', count: '{count}曲', emptyMusic: 'この端末にはまだお気に入りがありません。音楽ステーションで好きな曲を探しましょう。',
    emptyRecent: 'この端末の再生履歴はまだありません。', openMusic: '音楽ステーションへ', more: 'さらに表示',
    savedTrack: '保存した曲 {number}', trackMissing: '曲を利用できません（{id}）', trackUnavailable: '曲の情報を読み込めません（{id}）',
    musicCorrupt: '音楽データが破損しているか互換性がありません。元のデータは保持しています。音楽ページで確認してください。',
    musicStorage: 'このブラウザーの音楽データを読み込めないため、保存の有無を確認できません。',
    musicLegacy: '以前のローカルお気に入りを表示中です。このページでは書き換えません。',
    native: 'アプリの音楽ライブラリー', nativeIntro: 'アプリのお気に入りはアプリ内で確認してください。ブラウザーのお気に入りは自動でアプリに同期されません。',
    game: 'セーブと購入済みアイテム', gameIntro: '端末とクラウドのセーブは別々に表示します。同じ進行状況かどうかはゲーム内で確認してください。',
    gameOpen: 'ゲームでセーブを確認', local: '端末', cloud: 'クラウド', checking: '確認中…',
    identityError: '現在のアカウントを確認できません。もう一度確認してください。', guest: '未ログインです。この端末のゲストセーブを表示します。',
    missing: '現在のスロットにセーブがありません', valid: '読み取れる端末セーブがあります', corrupt: 'セーブが破損しています。元のデータは保持しています', unsupported: '非対応のセーブ形式です。元のデータは保持しています', unavailable: '端末の保存領域を読み込めません',
    cloudGuest: 'ログインするとクラウドセーブを確認できます', cloudMissing: 'このアカウントにはクラウドセーブがありません', cloudSaved: 'クラウドセーブあり · 版 {revision} · {date}', cloudError: 'クラウドセーブを確認できません',
    costumes: '購入済みアイテム：{count}件', costumesGuest: '購入済みアイテムはログイン後に確認できます', costumesError: '購入済みアイテムを確認できません',
    retry: '再確認', orders: '過去の注文', ordersIntro: '元の注文番号で支払いと受け取り状況を確認できます。アカウントに紐づく注文は元のアカウントでログインしてください。',
    orderLabel: '注文番号', orderSubmit: '注文を確認', orderRequired: '元の注文番号を80文字以内で入力してください。',
    orderFound: '{status} · {amount} {currency}', fulfilled: '受け取り完了', pending: '支払いまたは受け取りを確認中', review: '受け取りの個別確認が必要です', refunded: '返金または入金取り消し済み', failed: '支払い未完了', expired: '注文期限切れ',
    orderUnknown: '注文状況を確認できません', orderNotFound: '注文が見つかりません', orderAuth: '注文を所有するアカウントでログインしてください', orderOther: '別のアカウントの注文です', orderError: '注文を確認できません。しばらくしてから再試行してください。',
    support: 'アカウントとサポート', supportIntro: '過去の購入、ポイント、サポートの規則は引き続き適用されます。お問い合わせの際は元の注文番号をお手元に。',
    contact: 'サポートへ連絡', points: 'ポイントと返金の規則', privacy: 'プライバシー', terms: '利用規約',
    refreshSession: 'アカウントが変更されました。再確認してください。',
  },
});

export const memberText = (locale, key, values = {}) => String((memberCopy[locale] || memberCopy['zh-Hant'])[key] || '')
  .replace(/\{(\w+)\}/g, (match, name) => Object.hasOwn(values, name) ? String(values[name]) : match);
